namespace: trilio
name: trilio_openstack
version: 1.0.0
readme: README.md
authors:
  - Kevin Jackson
description: Ansible Collection for managing Trilio for OpenStack (Workload Manager) backup and recovery operations.
license:
  - Apache-2.0
tags:
  - openstack
  - cloud
  - backup
  - recovery
  - disaster_recovery
  - trilio
  - triliovault
  - workloadmgr
dependencies:
  openstack.cloud: ">=2.1.0"
repository: https://github.com/trilio-labs/trilio_openstack
documentation: https://docs.trilio.io/openstack
issues: https://github.com/trilio-labs/trilio_openstack/issues

